server: 
  port: 18001
spring: 
  application:  
    name: 2dmadmin #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.128:3306/mango?characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.31.128
  rabbitmq:
    host: 192.168.31.128
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.128:6868/eureka/
  instance:
    prefer-ip-address: true
    
 #文件存储路径
prop:
  upload-folder: /tmp/files/

  #设置最大上传大小为10Mb
  http:
    multipart:
      max-file-size: 10Mb
